name: Validate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get dancelist version
        run: echo "::set-output name=HEAD::$(git ls-remote https://github.com/qwandor/dancelist HEAD|cut -f1)"
        id: version
      - name: Cache .cargo and target
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: ${{ runner.os }}-cargo-install-${{ steps.version.outputs.HEAD }}
      - name: Install dancelist
        run: cargo install --git https://github.com/qwandor/dancelist
      - name: Validate
        run: dancelist validate events/
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check YAML and Markdown formatting
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_options: "--check **/*.{yaml,md}"
